name: Deploy

on:
  pull_request:
    branches:
      - stage
      - main
    types: [opened, reopened, synchronize, edited]

jobs:
  setup:
    runs-on: ubuntu-latest
    container: my-image-name:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Compose
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
        chmod +x /tmp/docker-compose
        sudo mv /tmp/docker-compose /usr/local/bin/docker-compose

    - name: Use Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci

  test:
    runs-on: ubuntu-latest
    container:
      image: my-image-name:latest
      volumes:
        - /path/to/setup/dir:/path/to/test/dir

    needs:
      - setup

    steps:
    - name: Tests
      run: npm run test

  compose-down:
    runs-on: ubuntu-latest
    needs:
      - setup
      - test

    steps:
    - name: Docker compose down
      run: docker-compose down --volumes
