name: Deploy

on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'
    branches:
      - stage
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Compose
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
        chmod +x /tmp/docker-compose
        sudo mv /tmp/docker-compose /usr/local/bin/docker-compose

    - name: Use Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci

  test:
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
    - name: Tests
      run: npm run test

    - name: Clean up
      run: docker-compose down --volumes
